# Generated by Django 3.0.8 on 2020-08-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Mens Clothes', 'Mens Clothes'), ('Womens Clothes', 'Womens Clothes'), ('Jwellery', 'Jwellery'), ('Toys', 'Toys'), ('Tech', 'Tech'), ('Other', 'Other')], max_length=14),
        ),
    ]
