# Generated by Django 3.0.8 on 2020-08-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200808_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Fashion', 'Fashion'), ('Jewellery', 'Jewellery'), ('Toys', 'Toys'), ('Electronics', 'Electronics'), ('Other', 'Other')], max_length=14),
        ),
    ]
